version: '3.8'

services:
  app:
    environment:
      APP_ENV: production
      APP_DEBUG: false
    volumes:
      - .:/var/www/html
    command: sh -c "composer install --no-dev --optimize-autoloader && npm install && npm run build && apache2-foreground"
