<?php

namespace App\Http\Controllers\Api\ApiInternal;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\Validator;
use Symfony\Component\Mime\Part\TextPart;
use Symfony\Component\Mime\Part\DataPart;
use Symfony\Component\Mime\Part\Multipart\AlternativePart;

class SendEmail extends Controller
{





public function sendOfferEmailPickup(Request $request)
{
    $request->validate([
        'subject' => 'required|string',
        'message' => 'required|string',
        'contacts' => 'required',
        'cc' => 'nullable|string',
        'attachment' => 'nullable|file|max:10240', // max 10MB
    ]);

    // Decode kontak utama (To:)
    $contacts = json_decode($request->contacts, true);
    $emails = collect($contacts)->pluck('email')->filter()->toArray();

    // Decode CC (jika ada)
    $ccArray = [];
    if (!empty($request->cc)) {
        $decoded = json_decode($request->cc, true);
        $ccArray = is_array($decoded) ? array_filter($decoded) : [];
    }

    if (empty($emails)) {
        return response()->json(['success' => false, 'message' => 'No valid recipient emails found.'], 400);
    }

    try {
    Mail::send([], [], function ($message) use ($request, $emails, $ccArray) {
        $message->to($emails)
                ->subject($request->subject);

        if (!empty($ccArray)) {
            $message->cc($ccArray);
        }

        // Konversi pesan dari user
        $body = nl2br(e($request->message));

        // Ambil logo dari public path
        $logoPath = public_path('images/logo.png'); // contoh: public/images/logo.png
        $logoCid = null;
        if (file_exists($logoPath)) {
            $logoCid = $message->embed($logoPath);
        } else {
            // fallback online jika logo lokal tidak ada
            // $logoCid = 'https://wpc-logistics.co.id/logo.png';
            $logoCid = 'https://res.cloudinary.com/dsrmldz7m/image/upload/v1761796928/logo_tzenge.png';

        }

        // Template email modern
        $htmlBody = '
        <div style="font-family:Arial,Helvetica,sans-serif; background-color:#f5f6fa; padding:30px;">
          <div style="max-width:640px; margin:auto; background:#fff; border-radius:8px; overflow:hidden; box-shadow:0 2px 8px rgba(0,0,0,0.08);">
            
            <!-- HEADER -->
            <div style="background-color:#003366; text-align:center; padding:25px 20px;">
                <img src="' . $logoCid . '" alt="WPC Logistics" style="max-width:140px; height:auto; display:inline-block; margin-bottom:10px;">
            </div>

            <!-- BODY -->
            <div style="padding:35px 40px; color:#333; font-size:14px; line-height:1.7;">
                <p>' . $body . '</p>
            </div>

            <div style="padding:35px 40px; color:#333; font-size:14px; line-height:1.7;">
               <p>Press the button below if you want to see the detailed list of quotations</p>
            </div>

            <div style="margin:10px 0;">
            <table border="0" cellspacing="0" cellpadding="0" align="left">
                <tr>
                <td bgcolor="#004aad" style="border-radius:9px;">
                    <a href="https://edu-wpc.odoo.com/my/" target="_blank"
                    style="display:inline-block; padding:5px 10px; font-family:Arial,Helvetica,sans-serif;
                    font-size:14px; color:#ffffff; text-decoration:none; font-weight:bold;">
                    View Quotation Online
                    </a>
                </td>
                </tr>
            </table>
            </div>

            <div style="padding:35px 40px; color:#333; font-size:14px; line-height:1.7;">
               <br><br>
            </div>

            <div style="padding:35px 40px; color:#333; font-size:14px; line-height:1.7;">
                <p>Best Regards,<br><br><br>
                WPC Logistics Team</p>
            </div>

            <!-- FOOTER -->
            <div style="background:#f0f0f0; padding:15px; text-align:center; font-size:12px; color:#555;">
                © ' . date('Y') . ' WPC Logistics |
                <a href="https://wpc-logistics.co.id" style="color:#003366; text-decoration:none;">wpc-logistics.co.id</a><br>
                <span style="color:#999;"> Email Generated BY System — Please do not reply directly.</span>
            </div>

          </div>
        </div>';

        $message->html($htmlBody);

        // Lampiran (jika ada)
        if ($request->hasFile('attachment')) {
            $message->attach(
                $request->file('attachment')->getRealPath(),
                [
                    'as' => $request->file('attachment')->getClientOriginalName(),
                    'mime' => $request->file('attachment')->getMimeType(),
                ]
            );
        }
    });

    return response()->json(['success' => true, 'message' => 'Email sent successfully']);
} catch (\Exception $e) {
    \Log::error('Email Send Error: ' . $e->getMessage(), ['exception' => $e]);
    return response()->json([
        'success' => false,
        'message' => 'Failed to send email. Error: ' . $e->getMessage()
    ], 500);
}

}





function sendOfferEmailDestination(Request $request){
     $request->validate([
        'subject' => 'required|string',
        'message' => 'required|string',
        'contacts' => 'required',
        'cc' => 'nullable|string',
        'attachment' => 'nullable|file|max:10240', // max 10MB
    ]);

    // Decode kontak utama (To:)
    $contacts = json_decode($request->contacts, true);
    $emails = collect($contacts)->pluck('email')->filter()->toArray();

    // Decode CC (jika ada)
    $ccArray = [];
    if (!empty($request->cc)) {
        $decoded = json_decode($request->cc, true);
        $ccArray = is_array($decoded) ? array_filter($decoded) : [];
    }

    if (empty($emails)) {
        return response()->json(['success' => false, 'message' => 'No valid recipient emails found.'], 400);
    }

    try {
    Mail::send([], [], function ($message) use ($request, $emails, $ccArray) {
        $message->to($emails)
                ->subject($request->subject);

        if (!empty($ccArray)) {
            $message->cc($ccArray);
        }

        // Konversi pesan dari user
        $body = nl2br(e($request->message));

        // Ambil logo dari public path
        $logoPath = public_path('images/logo.png'); // contoh: public/images/logo.png
        $logoCid = null;
        if (file_exists($logoPath)) {
            $logoCid = $message->embed($logoPath);
        } else {
            // fallback online jika logo lokal tidak ada
            // $logoCid = 'https://wpc-logistics.co.id/logo.png';
            $logoCid = 'https://res.cloudinary.com/dsrmldz7m/image/upload/v1761796928/logo_tzenge.png';

        }

        // Template email modern
        $htmlBody = '
        <div style="font-family:Arial,Helvetica,sans-serif; background-color:#f5f6fa; padding:30px;">
          <div style="max-width:640px; margin:auto; background:#fff; border-radius:8px; overflow:hidden; box-shadow:0 2px 8px rgba(0,0,0,0.08);">
            
            <!-- HEADER -->
            <div style="background-color:#003366; text-align:center; padding:25px 20px;">
                <img src="' . $logoCid . '" alt="WPC Logistics" style="max-width:140px; height:auto; display:inline-block; margin-bottom:10px;">
            </div>

            <!-- BODY -->
            <div style="padding:35px 40px; color:#333; font-size:14px; line-height:1.7;">
                <p>' . $body . '</p>
            </div>

            <div style="padding:35px 40px; color:#333; font-size:14px; line-height:1.7;">
               <p>Press the button below if you want to see the detailed list of quotations</p>
            </div>

            <div style="margin:10px 0;">
            <table border="0" cellspacing="0" cellpadding="0" align="left">
                <tr>
                <td bgcolor="#004aad" style="border-radius:9px;">
                    <a href="https://edu-wpc.odoo.com/my/" target="_blank"
                    style="display:inline-block; padding:5px 10px; font-family:Arial,Helvetica,sans-serif;
                    font-size:14px; color:#ffffff; text-decoration:none; font-weight:bold;">
                    View Quotation Online
                    </a>
                </td>
                </tr>
            </table>
            </div>

            <div style="padding:35px 40px; color:#333; font-size:14px; line-height:1.7;">
               <br><br>
            </div>

            <div style="padding:35px 40px; color:#333; font-size:14px; line-height:1.7;">
                <p>Best Regards,<br><br><br>
                WPC Logistics Team</p>
            </div>

            <!-- FOOTER -->
            <div style="background:#f0f0f0; padding:15px; text-align:center; font-size:12px; color:#555;">
                © ' . date('Y') . ' WPC Logistics |
                <a href="https://wpc-logistics.co.id" style="color:#003366; text-decoration:none;">wpc-logistics.co.id</a><br>
                <span style="color:#999;"> Email Generated BY System — Please do not reply directly.</span>
            </div>

          </div>
        </div>';

        $message->html($htmlBody);

        // Lampiran (jika ada)
        if ($request->hasFile('attachment')) {
            $message->attach(
                $request->file('attachment')->getRealPath(),
                [
                    'as' => $request->file('attachment')->getClientOriginalName(),
                    'mime' => $request->file('attachment')->getMimeType(),
                ]
            );
        }
    });

    return response()->json(['success' => true, 'message' => 'Email sent successfully']);
} catch (\Exception $e) {
    \Log::error('Email Send Error: ' . $e->getMessage(), ['exception' => $e]);
    return response()->json([
        'success' => false,
        'message' => 'Failed to send email. Error: ' . $e->getMessage()
    ], 500);
}

}



}